version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: "/home/postgres/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - ./data:/home/postgres/pgdata
    ports:
      - "${DB_PORT}:5432"