openapi: "3.0.2"
info:
  title: KApp
  version: "1.0"
servers:
  - url: http://0.0.0.0:8089
    description: dev stand
tags:
  - name: auth
    description: Authorisation
  - name: user
    description: All about users
  - name: recipe
    description: All about recipes
  - name: ingredient
    description: All about ingredients
paths:
  /auth/login:
    $ref: "auth.yml#/path/~1auth~1login"
  /auth/register:
    $ref: "auth.yml#/path/~1auth~1register"
  /auth/logout:
    $ref: "auth.yml#/path/~1auth~1logout"

  /users:
    $ref: "user.yml#/path/~1users"
  /users/{id}:
    $ref: "user.yml#/path/~1users~1{id}"
  /users/{id}/saved-recipes/{recipe_id}:
    $ref: "user.yml#/path/~1users~1{id}~1saved-recipes~1{recipe_id}"

  /recipes:
    $ref: "recipe.yml#/path/~1recipes"
  /recipes/{id}:
    $ref: "recipe.yml#/path/~1recipes~1{id}"
  /recipes/{id}/info:
    $ref: "recipe.yml#/path/~1recipes~1{id}~1info"
  /recipes/{id}/stages:
    $ref: "recipe.yml#/path/~1recipes~1{id}~1stages"
  /recipes/{id}/comments:
    $ref: "recipe.yml#/path/~1recipes~1{id}~1comments"
  /recipes/{id}/comments/{comment_id}:
    $ref: "recipe.yml#/path/~1recipes~1{id}~1comments~1{comment_id}"

  /ingredients:
    $ref: "ingredient.yml#/path/~1ingredients"
  /ingredients/{id}:
    $ref: "ingredient.yml#/path/~1ingredients~1{id}"

    
    
